### PR TITLE
The linuxbrew/brew Ubuntu Xenial image is now homebrew/brew

### PR DESCRIPTION
**Pull request by issyl0**

### CODE REVIEW

**Comment by issyl0** [comment]
There's no point maintaining two supposedly identical Dockerfiles with different names. In fact, they're currently out of sync.

**Review by sjackman — CHANGES_REQUESTED** [review]
These two Dockerfile are different. https://github.com/Homebrew/brew/blob/master/Dockerfile is `FROM ubuntu:xenial` (Ubuntu LTS 16.04) and this `bionic/Dockerifle` is `FROM ubuntu:bionic` (Ubuntu LTS 18.04).

**Comment by issyl0** [comment]
Ah, oops. https://github.com/Linuxbrew/docker/pull/61#discussion_r363125698 was wrong then.

**Comment by issyl0** [comment]
Is there a plan to bump Homebrew/brew's Dockerfile to use Ubuntu more-recent-than-16.04?

**Comment by sjackman** [comment]
> Is there a plan to bump Homebrew/brew's Dockerfile to use Ubuntu more-recent-than-16.04?

Yes, at some point, but no immediate plans. I'd like to maintain two Docker images, when for our CI, which could continue using Ubuntu 16.04, and one intended for use by end users, which could be upgraded to Ubuntu 18.04, and Ubuntu 20.04 soon enough. We use Ubuntu 16.04 to build bottles so that they can run on older systems.

**Comment by issyl0** [comment]
Thanks, Shaun. I deleted the Xenial Dockerfile here instead and fixed the references.

**Comment by maxim-belkin** [comment]
> Thanks, Sean.

:trollface:

**Comment by issyl0** [comment]
> > Thanks, Sean.
> 
> :trollface:

🤦‍♂

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
Thanks, Issy!

**Comment by issyl0** [comment]
I'm frankly surprised you didn't get me back with "Izzy".

**Comment by sjackman** [comment]
I thought of that exact thing right after I hit `Comment`. 😆

**Pull request merged**
