### PR TITLE
Rename ubuntu to xenial

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by bw-yuhogg** [comment]
The Makefile is incorrect now, I think.

If you don't find it useful, feel free to just get rid of it though.

**Comment by sjackman** [comment]
I've removed the Makefile. There's a `linuxbrew/ubuntu` image as well. Should we get rid of it? People should probably use `linuxbrew/linuxbrew` instead.

**Comment by bw-yuhogg** [comment]
If you feel Ubuntu should be the "default" for Linuxbrew, than yeah, making `linuxbrew/linuxbrew` the supported Ubuntu Docker image sounds good to me.

There should be some documentation in this repo about it though.

**Comment by sjackman** [comment]
Both images are built on `xenial`, so seem redundant, and `linuxbrew/linuxbrew` is more current. Good idea. I'll update the README.

**Comment by sjackman** [comment]
Done.

**Pull request merged**
