### PR TITLE
Add scratch

### PR DESCRIPTION
**Pull request by sjackman**
Build a Docker image of Linuxbrew from scratch.
Install Linuxbrew using only Linuxbrew bottles.

### CODE REVIEW

**Comment by sjackman** [comment]
Requires this patch of `linuxbrew/brew` to work:
```diff
diff --git a/Library/Homebrew/requirements/glibc_requirement.rb b/Library/Homebrew/requirements/glibc_requirement.rb
index e52bf23..56c3d3c 100644
--- a/Library/Homebrew/requirements/glibc_requirement.rb
+++ b/Library/Homebrew/requirements/glibc_requirement.rb
@@ -12,6 +12,7 @@ class GlibcRequirement < Requirement
     end
     raise "Unable to locate the system's glibc" unless libc
     version = Utils.popen_read("#{libc} 2>&1")[/[Vv]ersion (\d\.\d+)/, 1]
+    version = Utils.popen_read("/lib64/ld-linux-x86-64.so.2 #{libc} 2>&1")[/[Vv]ersion (\d\.\d+)/, 1] unless version
     raise "Unable to determine the system's glibc version" unless version
     @system_version = version
   end
```

**Comment by maxim-belkin** [comment]
I'd suggest using /bin/bash as sn entry point.

**Comment by sjackman** [comment]
`/bin/sh` is a symlink on this system to `bash`, but I vaguely recall `bash` starting in a compatibility mode if it's run as `sh` rather than `bash`. Does that ring any bells?

**Comment by sjackman** [comment]
Rather than using the above patch to `glibc_requirement`, I'd like to fix it so that being unable to determine the host version of `glibc` is only a warning, not an error. Alpine Linux does not have glibc at all, so that fix is needed for Alpine Linux.
See https://github.com/Linuxbrew/docker/pull/25

**Pull request merged**
